Auth ui
BuildForSDG/Team-209-Mobile pull request #5
Opened 2020-05-15 23:53 UTC by boyedokup

## Description

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(3) #(4)

## How Has This Been Tested?
Compared the design to UI/UX

## Screenshots (if applicable, else remove this line / section)
![image](https://user-images.githubusercontent.com/1927606/82104543-e07b5b00-9706-11ea-9f19-851a0f2e0288.png)
![image](https://user-images.githubusercontent.com/1927606/82104577-fa1ca280-9706-11ea-87fa-113b8a154e29.png)
![image](https://user-images.githubusercontent.com/1927606/82104594-102a6300-9707-11ea-841f-d2095aad8879.png)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-16 06:08 UTC, paajake requested changes

2020-05-16 06:08 UTC, paajake commented on src/app/service/auth.service.ts
> +        localStorage.removeItem('auth_user');
You should make a post request to the /api/logout end point to also remove the token from the backend, when logging out

2020-05-16 06:41 UTC, paajake requested changes

2020-05-16 06:41 UTC, paajake commented on src/app/register/register.page.html
> +                    Mobile Number</ion-label>
Hide/comment out mobile numbers for now

2020-05-16 17:07 UTC, paajake commented
Please test the auth and confirm it's working with the live backend on Heroku

2020-05-21 19:01 UTC, boyedokup commented
Added the updates to the next pull request

2020-05-22 10:55 UTC, paajake requested changes
Wouldn't it be better just to ignore all the IDE and build files? like .idea/

2020-05-22 10:55 UTC, paajake commented on src/app/register/register.page.html
> +                    Password</ion-label>
Add a password_confirmation field

2020-05-25 08:41 UTC, paajake approved these changes

2020-05-25 08:42 UTC, merged